### ISSUE TITLE
Falar um pouco sobre o rails

### ISSUE THREAD

**Issue by JVictorV** [edersonferreira/ruby4noobs#1]
Como e o principal framework da linguagem e muito utilizado acho valido falar um pouco sobre

**Comment by lissarubi** [comment]
Acho interessante sim, mas este repositório é dedicado ao Ruby, ainda estou aprendendo e irei fazer um 4noobs de Rails, mas acho que irei colocar um trecho explicando sobre o Rails, pois a maioria das pessoas aprendem Ruby por causa do Rails, obrigado.

**Comment by d3c0d3d** [comment]
@edersonferreira Concordo! Ate porque existe varios outros frameworks tão bom quanto o Rails!

**Comment by lissarubi** [comment]
No último commit adicionei um tópico bônus sobre Rails, obrigado pela sugestão!
