### ISSUE TITLE
Gerenciador de Pacotes do Ruby

### ISSUE THREAD

**Issue by d3c0d3d** [edersonferreira/ruby4noobs#2]
Como sujestão acho valido falar um pouco sobre o gerenciador de pacotes do ruby 'RubyGems' já que praticamente todas as linguagens atuais tem seus gerenciadores de pacotes!!

**Comment by lissarubi** [comment]
Boa ideia, irei colocar isso no ruby4noobs daqui no máximo alguns dias, obrigado.

**Comment by lissarubi** [comment]
Adicionei Ruby Gems no último commit, valeu pela sugestão!
