### ISSUE TITLE
Meus parabéns!

### ISSUE THREAD

**Issue by odaviribeiro** [edersonferreira/ruby4noobs#3]
Tinha curiosidade de aprender a linguagem mas nunca tinha parado para estudar ela e sua documentação ficou muito boa!

Comecarei a estudar ela e quem sabe utilizar em meus projetos, curti demais a lang! Meus parabéns de novo!

**Comment by lissarubi** [comment]
Obrigado cara, Valeu, boa programação aí! Vê o de Rails também, é praticamente uma tradução do Getting Start da documentação original!
