### ISSUE TITLE
ternário

### ISSUE THREAD

**Issue by tomilico** [edersonferreira/ruby4noobs#9]
tu pode por nas estruturas condicionais o operador ternário? eu procurei na internet porem fiquei meio confuso em meio aos exemplos e nao consegui executar direito

**Comment by hudson0xf** [comment]
O operador ternário performa como qualquer operação de três operandos, o que significa que você pode colocar outras operações dentro de uma operação ternária, por exemplo:

```ruby
x, y = 10, 40

x == 10 ? (y > 30 ? puts("x é igual a 10 e y maior que 30") : puts("x é igual a 10 e y menor que 30")) : (puts("n não é igual a 10"))
```
O exemplo acima é uma operação ternária dentro de outra operação ternária, utilizando if-else ficaria desta forma:

```ruby
x, y = 10, 40

if x == 10
	if y > 30
		puts("x é igual a 10 e y maior que 30")
	else
		puts("x é igual a 10 e y menor que 30")
	end
else
	puts("x não é igual a 10")
end
```
